export {crearDeck} from "./crear-deck"
export {pedirCarta} from "./pedir-carta"
export {valorCarta} from "./valor-carta"
export {acumularPuntos} from "./acumular-puntos"
export {turnoComputadora} from "./turno-computadora"
export {determinarGanadaor} from "./determinar-ganador"
export {crearCarta} from "./crear-carta"